### ISSUE TITLE
Plot clear causes exception

### ISSUE THREAD

**Issue by SBPrime** [WorldCretornica/PlotMe-Core#103]
I was testing plotMe progressive clear.

After invoking ___/plot clear___ there was no message. The console started logging:

    [13:25:52 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a50.0k§r/§a2.0M§r blocks)
    [13:26:02 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a100.0k§r/§a2.0M§r blocks)
    [13:26:12 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a150.0k§r/§a2.0M§r blocks)

Since I did not notice that something was displayed on the console i typed ___/plot clear___ again.

Console output:

    [13:26:19 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a50.0k§r/§a2.0M§r blocks)
    [13:26:22 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a200.0k§r/§a2.0M§r blocks)
    [13:26:29 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a100.0k§r/§a2.0M§r blocks)
    [13:26:32 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a250.0k§r/§a2.0M§r blocks)
    [13:26:39 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a150.0k§r/§a2.0M§r blocks)
    [13:26:42 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a300.0k§r/§a2.0M§r blocks)
    [13:26:49 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a200.0k§r/§a2.0M§r blocks)
    [13:26:52 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a350.0k§r/§a2.0M§r blocks)

Then after a while:

    [13:34:21 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a2.0M§r/§a2.0M§r blocks)
    [13:34:23 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a2.0M§r/§a2.0M§r blocks)
    [13:34:31 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a2.0M§r/§a2.0M§r blocks)
    [13:34:33 WARN]: [PlotMe] Task #14 for PlotMe v0.15.2 generated an exception
        java.lang.NullPointerException
            at com.worldcretornica.plotme_core.PlotMeSpool.getDoneBlocks(PlotMeSpool.java:95) ~[?:?]
            at com.worldcretornica.plotme_core.PlotMeSpool.showProgress(PlotMeSpool.java:77) ~[?:?]
            at com.worldcretornica.plotme_core.PlotMeSpool.run(PlotMeSpool.java:57) ~[?:?]
            at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-20141001a.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
            at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-20141001a.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
            at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641) [spigot-20141001a.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
            at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-20141001a.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
            at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-20141001a.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
            at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-20141001a.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
            at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-20141001a.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    [13:34:41 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a2.0M§r/§a2.0M§r blocks)
    [13:34:43 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a50.0k§r/§a2.0M§r blocks)
    [13:34:51 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a2.0M§r/§a2.0M§r blocks)
    [13:34:53 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a100.0k§r/§a2.0M§r blocks)
    [13:35:01 WARN]: [PlotMe] Task #15 for PlotMe v0.15.2 generated an exception
    java.lang.NullPointerException
            at com.worldcretornica.plotme_core.PlotMeSpool.getDoneBlocks(PlotMeSpool.java:95)     ~[?:?]
            at com.worldcretornica.plotme_core.PlotMeSpool.showProgress(PlotMeSpool.java:77) ~[?:?]
            at com.worldcretornica.plotme_core.PlotMeSpool.run(PlotMeSpool.java:57) ~[?:?]
            at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-20141001a.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
            at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-20141001a.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
            at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641) [spigot-20141001a.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
            at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-20141001a.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
            at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-20141001a.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
            at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-20141001a.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
            at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-20141001a.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    [13:35:03 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a150.0k§r/§a2.0M§r blocks)
    [13:35:11 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a50.0k§r/§a2.0M§r blocks)
    [13:35:13 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a200.0k§r/§a2.0M§r blocks)
    [13:35:21 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a100.0k§r/§a2.0M§r blocks)

After a clean startup:

    [13:50:39 INFO]: SBPrime issued server command: /plot clear
    [13:50:39 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a50.0k§r/§a2.0M§r blocks)
    [13:50:49 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a100.0k§r/§a2.0M§r blocks)
    [13:50:59 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a150.0k§r/§a2.0M§r blocks)
    [13:51:09 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a200.0k§r/§a2.0M§r blocks)
    ...
    [13:55:50 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a1.0M§r/§a2.0M§r blocks)
    [13:56:00 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a1.0M§r/§a2.0M§r blocks)
    [13:56:10 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a1.0M§r/§a2.0M§r blocks)
    [13:56:20 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a1.0M§r/§a2.0M§r blocks)
    [13:56:30 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a1.0M§r/§a2.0M§r blocks)
    ...
    [13:59:01 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a2.0M§r/§a2.0M§r blocks)
    [13:59:11 WARN]: [PlotMe] Task #10 for PlotMe v0.15.2 generated an exception
    java.lang.NullPointerException
            at com.worldcretornica.plotme_core.PlotMeSpool.getDoneBlocks(PlotMeSpool.java:95) ~[?:?]
            at com.worldcretornica.plotme_core.PlotMeSpool.showProgress(PlotMeSpool.java:77) ~[?:?]
            at com.worldcretornica.plotme_core.PlotMeSpool.run(PlotMeSpool.java:57) ~[?:?]
            at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-20141001a.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
            at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-20141001a.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
            at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641) [spigot-20141001a.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
            at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-20141001a.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
            at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-20141001a.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
            at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-20141001a.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
            at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-20141001a.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    [13:59:21 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a50.0k§r/§a2.0M§r blocks)
    [13:59:31 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a100.0k§r/§a2.0M§r blocks)
    [13:59:41 INFO]: [PlotMe] Plot §a0;0§r in §aworld§r is §a0% §rcleared (§a150.0k§r/§a2.0M§r blocks)
    ...

**Comment by MattBDev** [comment]
Thanks for the report. I like how you made it detailed :)

**Comment by MattBDev** [comment]
@ZachBora has fixed this in commit 2c044db5aa541eedea18b5e8c8735c7f3483d7f5
