### ISSUE TITLE
Problem at the start.

### ISSUE THREAD

**Issue by darkrider84** [WorldCretornica/PlotMe-Core#163]
Hello.
This errors comes if I start the server: 

[23:14:29] [Server thread/WARN]: [PlotMe] You are using an unsupported version of worldedit. The PlotMe WorldEdit Listener not be enabled.

[23:15:13] [pool-3-thread-2/WARN]: Exception in thread "pool-3-thread-2" 
[23:15:13] [pool-3-thread-2/WARN]: org.apache.commons.lang.UnhandledException: Plugin PlotMe v0.16.2 generated an exception while executing task 5
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()Ljava/util/Collection;
	at com.worldcretornica.plotme_core.Metrics.postPlugin(Metrics.java:335)
	at com.worldcretornica.plotme_core.Metrics.access$400(Metrics.java:57)
	at com.worldcretornica.plotme_core.Metrics$1.run(Metrics.java:223)
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:53)
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

[23:15:14] [Server thread/INFO]: [NoCheatPlus] Post-enable running...
[23:15:17] [Server thread/INFO]: [NoCheatPlus] Post-enable finished.
[23:15:17] [pool-3-thread-5/WARN]: Exception in thread "pool-3-thread-5" 
[23:15:17] [pool-3-thread-5/WARN]: org.apache.commons.lang.UnhandledException: Plugin PlotMe-DefaultGenerator v0.16.1 generated an exception while executing task 8
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()Ljava/util/Collection;
	at com.worldcretornica.plotme_core.Metrics.postPlugin(Metrics.java:335)
	at com.worldcretornica.plotme_core.Metrics.access$400(Metrics.java:57)
	at com.worldcretornica.plotme_core.Metrics$1.run(Metrics.java:223)
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:53)
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

How can i fix it?

**Comment by MattBDev** [comment]
What version of bukkit are you using?

**Comment by darkrider84** [comment]
Build #3092 1.7.9 R-0.2 (beta)

**Comment by MattBDev** [comment]
I would try upgrading to 1.8 if you can because this is an issue with your version of CraftBukkit

**Comment by darkrider84** [comment]
I  cant upgrade... There are too many issues.

**Comment by MattBDev** [comment]
I sadly can't support your build of bukkit. I don't have access to it and I believe the issue also stems from metrics R0.2 is too old of a 1.7.9 build.
