### ISSUE TITLE
Unable to create Plotme World

### ISSUE THREAD

**Issue by Koz4Christ** [WorldCretornica/PlotMe-Core#171]
I am running Spigot 1.8-R0.1 (8a983f9-9ae3381) and plotme 16.2 but I am unable to create a new plots world (plotme world).  I even added the entry into bukkit.yml.  Here is the error message I get

[22:28:58] [Server thread/INFO]: Koz4Christ issued server command: /mv create plots normal -g PlotMe-DefaultGenerator
[22:28:58] [Server thread/INFO]: Koz4Christ: Starting creation of world 'plots'...[m
[22:28:58] [Server thread/INFO]: [Multiverse-Core] Loading World & Settings - 'plots' - Env: NORMAL - Type: NORMAL & generator: PlotMe-DefaultGenerator
[22:28:58] [Server thread/INFO]: -------- World Settings For [plots] --------
[22:28:58] [Server thread/INFO]: Item Despawn Rate: 6000
[22:28:58] [Server thread/INFO]: Item Merge Radius: 2.5
[22:28:58] [Server thread/INFO]: Arrow Despawn Rate: 1200
[22:28:58] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[22:28:58] [Server thread/INFO]: Chunks to Grow per Tick: 650
[22:28:58] [Server thread/INFO]: Clear tick list: false
[22:28:58] [Server thread/INFO]: Experience Merge Radius: 3.0
[22:28:58] [Server thread/INFO]: View Distance: 10
[22:28:58] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[22:28:58] [Server thread/INFO]: Cactus Growth Modifier: 100%
[22:28:58] [Server thread/INFO]: Cane Growth Modifier: 100%
[22:28:58] [Server thread/INFO]: Melon Growth Modifier: 100%
[22:28:58] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[22:28:58] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[22:28:58] [Server thread/INFO]: Sapling Growth Modifier: 100%
[22:28:58] [Server thread/INFO]: Wheat Growth Modifier: 100%
[22:28:58] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[22:28:58] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[22:28:58] [Server thread/INFO]: Anti X-Ray: true
[22:28:58] [Server thread/INFO]: 	Engine Mode: 1
[22:28:58] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[22:28:58] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[22:28:58] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[22:28:58] [Server thread/INFO]: Mob Spawn Range: 4
[22:28:58] [Server thread/INFO]: Alternative Hopper Ticking: false
[22:28:58] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[22:28:58] [Server thread/INFO]: Random Lighting Updates: false
[22:28:58] [Server thread/INFO]: Structure Info Saving: true
[22:28:58] [Server thread/INFO]: Sending up to 10 chunks per packet
[22:28:58] [Server thread/INFO]: Max Entity Collisions: 8
[22:28:58] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[22:28:58] [Server thread/INFO]: Max TNT Explosions: 100
[22:28:58] [Server thread/INFO]: Preparing start region for level 2 (Seed: 6422137582797236562)
[22:28:58] [Server thread/WARN]: net.minecraft.server.v1_8_R1.ReportedException: Exception generating new chunk
[22:28:58] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:148)
[22:28:58] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116)
[22:28:58] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:95)
[22:28:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.createWorld(CraftServer.java:920)
[22:28:58] [Server thread/WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:463)
[22:28:58] [Server thread/WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[22:28:58] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:421)
[22:28:58] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:229)
[22:28:58] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114)
[22:28:58] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[22:28:58] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[22:28:58] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[22:28:58] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:894)
[22:28:58] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[22:28:58] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[22:28:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[22:28:58] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
[22:28:58] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
[22:28:58] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[22:28:58] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
[22:28:58] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[22:28:58] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[22:28:58] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[22:28:58] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:685)
[22:28:58] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[22:28:58] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[22:28:58] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
[22:28:58] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[22:28:58] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[22:28:58] [Server thread/WARN]: 	at com.worldcretornica.plotme.defaultgenerator.DefaultChunkGenerator.generateExtBlockSections(DefaultChunkGenerator.java:47)
[22:28:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:53)
[22:28:58] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:140)
[22:28:58] [Server thread/WARN]: 	... 27 more
[22:28:58] [Server thread/ERROR]: [Multiverse-Core] The world 'plots' could NOT be loaded because it contains errors!
[22:28:58] [Server thread/ERROR]: [Multiverse-Core] Try using Chukster to repair your world! 'plots'
[22:28:58] [Server thread/ERROR]: [Multiverse-Core] http://forums.bukkit.org/threads/admin-chunkster.8186/
[22:28:58] [Server thread/ERROR]: [Multiverse-Core] Failed to Create/Load the world 'plots'
[22:28:58] [Server thread/INFO]: Koz4Christ: FAILED.[m

My bukkit.yml file
worlds:
  Prison:
    generator: CleanroomGenerator:.
  plots:
    generator: PlotMe-DefaultGenerator

**Comment by greeves12** [comment]
Hey aren't you that guy that does a bunch of plugins?

**Comment by greeves12** [comment]
Also to fix your issue the name of the world shouldnt be "plots" you cannot modify the name so put it back to plotworld and everything should work fine

**Comment by greeves12** [comment]
And if that doesnt fix it. Go into plotme folder then plotme generator folder then click config now look for the name "plotworld' and change that to "plots"

**Comment by MattBDev** [comment]
@greeves12  is right and has explained the issue well. Ticket closed
