### ISSUE TITLE
/p h returning errors (on dev #75)

### ISSUE THREAD

**Issue by PrisonHeist** [WorldCretornica/PlotMe-Core#175]
[01:10:29 INFO]: PH_Joe issued server command: /p h
[01:10:29 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'p' i
n plugin PlotMe v0.17-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spi
got-1.7.10-R0.1-SNAPSHOT-1647.jar:git-Spigot-1646]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:18
1) ~[spigot-1.7.10-R0.1-SNAPSHOT-1647.jar:git-Spigot-1646]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServe
r.java:767) ~[spigot-1.7.10-R0.1-SNAPSHOT-1647.jar:git-Spigot-1646]
        at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerCon
nection.java:1043) [spigot-1.7.10-R0.1-SNAPSHOT-1647.jar:git-Spigot-1646]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java
:880) [spigot-1.7.10-R0.1-SNAPSHOT-1647.jar:git-Spigot-1646]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java
:28) [spigot-1.7.10-R0.1-SNAPSHOT-1647.jar:git-Spigot-1646]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat
.java:65) [spigot-1.7.10-R0.1-SNAPSHOT-1647.jar:git-Spigot-1646]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186
) [spigot-1.7.10-R0.1-SNAPSHOT-1647.jar:git-Spigot-1646]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java
:81) [spigot-1.7.10-R0.1-SNAPSHOT-1647.jar:git-Spigot-1646]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:7
34) [spigot-1.7.10-R0.1-SNAPSHOT-1647.jar:git-Spigot-1646]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:2
89) [spigot-1.7.10-R0.1-SNAPSHOT-1647.jar:git-Spigot-1646]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:5
84) [spigot-1.7.10-R0.1-SNAPSHOT-1647.jar:git-Spigot-1646]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java
:490) [spigot-1.7.10-R0.1-SNAPSHOT-1647.jar:git-Spigot-1646]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:6
28) [spigot-1.7.10-R0.1-SNAPSHOT-1647.jar:git-Spigot-1646]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
        at org.sqlite.PrepStmt.batch(PrepStmt.java:173) ~[spigot-1.7.10-R0.1-SNA
PSHOT-1647.jar:git-Spigot-1646]
        at org.sqlite.PrepStmt.setString(PrepStmt.java:254) ~[spigot-1.7.10-R0.1
-SNAPSHOT-1647.jar:git-Spigot-1646]
        at com.worldcretornica.plotme_core.SqlManager.getPlayerPlots(SqlManager.
java:1564) ~[?:?]
        at com.worldcretornica.plotme_core.SqlManager.getOwnedPlots(SqlManager.j
ava:1500) ~[?:?]
        at com.worldcretornica.plotme_core.commands.CmdHome.exec(CmdHome.java:80
) ~[?:?]
        at com.worldcretornica.plotme_core.bukkit.BukkitCommand.onCommand(Bukkit
Command.java:223) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spi
got-1.7.10-R0.1-SNAPSHOT-1647.jar:git-Spigot-1646]
        ... 13 more

**Comment by MattBDev** [comment]
Please use Markdown format the next time you submit because just copying and pasting makes it extremely difficult for me to read.

**Comment by MattBDev** [comment]
I can't reproduce this. I am not sure how this is an ArrayIndexOutOfBoundsException when there is no array on line 1564

**Comment by PrisonHeist** [comment]
Any ideas what this could be? I've tried regenerating the database, have tried different version of the plugin and have also messed around with my configurations. All commands work except from /plotme home (or variations of this command).

**Comment by PrisonHeist** [comment]
Update: Build #72 (09-Feb-2015 15:12:39) and below work fine, it's #73 onwards that don't, I assume since the lowercase conversion.

**Comment by MattBDev** [comment]
now this helps a little more. Thanks for the info

**Comment by MattBDev** [comment]
I still can't reproduce but Wait for the next dev build I produce. Also, don't use the # symbol before the build number because it references a previous issue in github.

**Comment by PrisonHeist** [comment]
Will give it a go with the next build, should I update on this issue or create a new one if it still doesn't work? also sorry about that didn't realise.

**Comment by MattBDev** [comment]
Not a big issue. I would create another ticket in a few released. The plugin is about to get a bit buggy in my next few commits.
