### ISSUE TITLE
2 bugs with plotme_core

### ISSUE THREAD

**Issue by GreatGBL** [WorldCretornica/PlotMe-Core#208]
[05:07:27] [Craft Scheduler Thread - 1556/WARN]: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.mojang.com/profiles/minecraft
[05:07:27] [Craft Scheduler Thread - 1556/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[05:07:27] [Craft Scheduler Thread - 1556/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[05:07:27] [Craft Scheduler Thread - 1556/WARN]: 	at com.worldcretornica.plotme_core.utils.UUIDFetcher.call(UUIDFetcher.java:112)
[05:07:27] [Craft Scheduler Thread - 1556/WARN]: 	at com.worldcretornica.plotme_core.utils.UUIDFetcher.getUUIDOf(UUIDFetcher.java:91)
[05:07:27] [Craft Scheduler Thread - 1556/WARN]: 	at com.worldcretornica.plotme_core.SqlManager$3.run(SqlManager.java:2225)
[05:07:27] [Craft Scheduler Thread - 1556/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
[05:07:27] [Craft Scheduler Thread - 1556/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[05:07:27] [Craft Scheduler Thread - 1556/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[05:07:27] [Craft Scheduler Thread - 1556/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[05:07:27] [Craft Scheduler Thread - 1556/WARN]: 	at java.lang.Thread.run(Unknown Source)

The Second one : Some of player's sugar cane or other crop will disapear without anyreason, It will happen in a ramdon place.

**Comment by GreatGBL** [comment]
additional：  my server is 1.8.1 spigot online(not offline) server , use the 0.16.3 version plot plugin

**Comment by MattBDev** [comment]
The first one is an error connecting to Mojang and I have no control over that. The second issue is something that doesn't seem like it is caused by plotme.

**Comment by jomo** [comment]
The first one is a 400 response, which means [Bad Request](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_Error). All 4xx errors are **client** errors.
For some reason you created a malformed request.

Was there any other PlotMe log before the error @GreatGBL?

**Comment by MattBDev** [comment]
@jomo I have continuously been unable to reproduce the 400 error. I will continue trying to find it

**Comment by GreatGBL** [comment]
@MattBDev 
Thanks for your help , I think the second issuse caused by Framing Protect plugin, I will check

**Comment by jomo** [comment]
Hmm, I can confirm Mojang returns 400s for no valid reason. It's very rare, but it does happen.
You could just catch these errors and try again 1 more time, that will most likely fix it.
