### ISSUE TITLE
Plotme 1.7.10 errors  Help 

### ISSUE THREAD

**Issue by hamhamfreak** [WorldCretornica/PlotMe-Core#213]
[14:06:46] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to PlotMe v0.13f
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.7.10.jar:git-Spigot-1627]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.7.10.jar:git-Spigot-1627]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.7.10.jar:git-Spigot-1627]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.7.10.jar:git-Spigot-1627]
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.teleport(CraftPlayer.java:472) [spigot-1.7.10.jar:git-Spigot-1627]
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftEntity.teleport(CraftEntity.java:200) [spigot-1.7.10.jar:git-Spigot-1627]
	at com.worldcretornica.plotme.PMCommand.home(PMCommand.java:2199) [PlotMe.jar:?]
	at com.worldcretornica.plotme.PMCommand.onCommand(PMCommand.java:155) [PlotMe.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.7.10.jar:git-Spigot-1627]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [spigot-1.7.10.jar:git-Spigot-1627]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1013) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:850) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10.jar:git-Spigot-1627]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getMask()Lcom/sk89q/worldedit/masks/Mask;
	at com.worldcretornica.plotme.PlotWorldEdit.setMask(PlotWorldEdit.java:61) ~[?:?]
	at com.worldcretornica.plotme.PlotWorldEdit.setMask(PlotWorldEdit.java:18) ~[?:?]
	at com.worldcretornica.plotme.listener.PlotWorldEditListener.onPlayerTeleport(PlotWorldEditListener.java:107) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot-1.7.10.jar:git-Spigot-1627]
	... 21 more
[14:06:46] [Server thread/INFO]: ShockeyBear issued server command: /spawn
[14:06:46] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to PlotMe v0.13f
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.7.10.jar:git-Spigot-1627]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.7.10.jar:git-Spigot-1627]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.7.10.jar:git-Spigot-1627]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.7.10.jar:git-Spigot-1627]
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.teleport(CraftPlayer.java:472) [spigot-1.7.10.jar:git-Spigot-1627]
	at com.earth2me.essentials.Teleport.now(Teleport.java:113) [Essentials.jar:?]
	at com.earth2me.essentials.Teleport.teleport(Teleport.java:194) [Essentials.jar:?]
	at com.earth2me.essentials.Teleport.teleportPlayer(Teleport.java:158) [Essentials.jar:?]
	at com.earth2me.essentials.spawn.Commandspawn.respawn(Commandspawn.java:68) [EssentialsSpawn.jar:?]
	at com.earth2me.essentials.spawn.Commandspawn.run(Commandspawn.java:39) [EssentialsSpawn.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:149) [Essentials.jar:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:505) [Essentials.jar:?]
	at com.earth2me.essentials.spawn.EssentialsSpawn.onCommand(EssentialsSpawn.java:72) [EssentialsSpawn.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.7.10.jar:git-Spigot-1627]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [spigot-1.7.10.jar:git-Spigot-1627]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1013) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:850) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10.jar:git-Spigot-1627]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getMask()Lcom/sk89q/worldedit/masks/Mask;
	at com.worldcretornica.plotme.PlotWorldEdit.setMask(PlotWorldEdit.java:61) ~[?:?]
	at com.worldcretornica.plotme.PlotWorldEdit.setMask(PlotWorldEdit.java:18) ~[?:?]
	at com.worldcretornica.plotme.listener.PlotWorldEditListener.onPlayerTeleport(PlotWorldEditListener.java:107) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot-1.7.10.jar:git-Spigot-1627]
	... 26 more
[14:06:47] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to PlotMe v0.13f
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.7.10.jar:git-Spigot-1627]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.7.10.jar:git-Spigot-1627]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.7.10.jar:git-Spigot-1627]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:447) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:436) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.PacketPlayInFlying.a(SourceFile:137) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.PacketPlayInPosition.handle(SourceFile:63) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10.jar:git-Spigot-1627]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getMask()Lcom/sk89q/worldedit/masks/Mask;
	at com.worldcretornica.plotme.PlotWorldEdit.setMask(PlotWorldEdit.java:61) ~[?:?]
	at com.worldcretornica.plotme.PlotWorldEdit.setMask(PlotWorldEdit.java:18) ~[?:?]
	at com.worldcretornica.plotme.listener.PlotWorldEditListener.onPlayerTeleport(PlotWorldEditListener.java:107) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot-1.7.10.jar:git-Spigot-1627]
	... 14 more
[14:06:47] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to PlotMe v0.13f
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.7.10.jar:git-Spigot-1627]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.7.10.jar:git-Spigot-1627]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.7.10.jar:git-Spigot-1627]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:447) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:436) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.PacketPlayInFlying.a(SourceFile:137) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.PacketPlayInFlying.handle(SourceFile:8) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10.jar:git-Spigot-1627]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getMask()Lcom/sk89q/worldedit/masks/Mask;
	at com.worldcretornica.plotme.PlotWorldEdit.setMask(PlotWorldEdit.java:61) ~[?:?]
	at com.worldcretornica.plotme.PlotWorldEdit.setMask(PlotWorldEdit.java:18) ~[?:?]
	at com.worldcretornica.plotme.listener.PlotWorldEditListener.onPlayerTeleport(PlotWorldEditListener.java:107) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot-1.7.10.jar:git-Spigot-1627]
	... 14 more
[14:06:47] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to PlotMe v0.13f
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.7.10.jar:git-Spigot-1627]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.7.10.jar:git-Spigot-1627]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.7.10.jar:git-Spigot-1627]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:447) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:436) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.PacketPlayInFlying.a(SourceFile:137) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.PacketPlayInPosition.handle(SourceFile:63) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-1.7.10.jar:git-Spigot-1627]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10.jar:git-Spigot-1627]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getMask()Lcom/sk89q/worldedit/masks/Mask;
	at com.worldcretornica.plotme.PlotWorldEdit.setMask(PlotWorldEdit.java:61) ~[?:?]
	at com.worldcretornica.plotme.PlotWorldEdit.setMask(PlotWorldEdit.java:18) ~[?:?]
	at com.worldcretornica.pl

**Comment by MattBDev** [comment]
You are using an unsupported and outdated version of plotme. Please do not report errors for an old version. If you do report errors, use markdown format because posting like you did is really annoying.
