### ISSUE TITLE
Multiple Null Pointer Exceptions

### ISSUE THREAD

**Issue by oloflarsson** [WorldCretornica/PlotMe-Core#226]
```
`[11:55:51 INFO]: -------- World Settings For [mplotme1] --------
[11:55:51 INFO]: Item Despawn Rate: 6000
[11:55:51 INFO]: Item Merge Radius: 2.5
[11:55:51 INFO]: Arrow Despawn Rate: 1200
[11:55:51 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[11:55:51 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[11:55:51 INFO]: Max Entity Collisions: 8
[11:55:51 INFO]: Experience Merge Radius: 3.0
[11:55:51 INFO]: Chunks to Grow per Tick: 650
[11:55:51 INFO]: Clear tick list: false
[11:55:51 INFO]: Zombie Aggressive Towards Villager: true
[11:55:51 INFO]: View Distance: 10
[11:55:51 INFO]: Mob Spawn Range: 4
[11:55:51 INFO]: Anti X-Ray: true
[11:55:51 INFO]:        Engine Mode: 1
[11:55:51 INFO]:        Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[11:55:51 INFO]:        Replace Blocks: [1, 5]
[11:55:51 INFO]: Nerfing mobs spawned from spawners: false
[11:55:51 INFO]: Cactus Growth Modifier: 100%
[11:55:51 INFO]: Cane Growth Modifier: 100%
[11:55:51 INFO]: Melon Growth Modifier: 100%
[11:55:51 INFO]: Mushroom Growth Modifier: 100%
[11:55:51 INFO]: Pumpkin Growth Modifier: 100%
[11:55:51 INFO]: Sapling Growth Modifier: 100%
[11:55:51 INFO]: Wheat Growth Modifier: 100%
[11:55:51 INFO]: Alternative Hopper Ticking: false
[11:55:51 INFO]: Hopper Transfer: 64 Hopper Check: 64 Hopper Amount: 64
[11:55:51 INFO]: Sending up to 10 chunks per packet
[11:55:51 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[11:55:51 INFO]: Max TNT Explosions: 100
[11:55:51 INFO]: Random Lighting Updates: false
[11:55:51 INFO]: Entity Activation Range: An 24 / Mo 24 / Mi 12
[11:55:51 INFO]: Structure Info Saving: true
[11:55:51 INFO]: Tile Max Tick Time: 20ms Entity max Tick Time: 10ms
[11:55:51 INFO]: WorldInitEvent for mplotme1
[11:55:51 INFO]: Preparing start region for level 1 (Seed: 0)
[11:55:51 WARN]: net.minecraft.server.v1_8_R1.ReportedException: Exception generating new chunk
[11:55:51 WARN]:        at net.minecraft.server.v1_8_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:148)
[11:55:51 WARN]:        at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116)
[11:55:51 WARN]:        at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:95)
[11:55:51 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.createWorld(CraftServer.java:920)
[11:55:51 WARN]:        at org.bukkit.Bukkit.createWorld(Bukkit.java:463)
[11:55:51 WARN]:        at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[11:55:51 WARN]:        at com.massivecraft.massivesharding.entity.MWorld.createOnThisServer(MWorld.java:568)
[11:55:51 WARN]:        at com.massivecraft.massivesharding.entity.wp.WPEnabled.doEnable(WPEnabled.java:65)
[11:55:51 WARN]:        at com.massivecraft.massivesharding.entity.wp.WPEnabled.apply(WPEnabled.java:44)
[11:55:51 WARN]:        at com.massivecraft.massivesharding.entity.wp.WorldPropertyBoolean.apply(WorldPropertyBoolean.java:1)
[11:55:51 WARN]:        at com.massivecraft.massivesharding.entity.wp.WorldProperty.apply(WorldProperty.java:253)
[11:55:51 WARN]:        at com.massivecraft.massivesharding.entity.MWorld.applyAll(MWorld.java:508)
[11:55:51 WARN]:        at com.massivecraft.massivesharding.entity.MWorldColl.applyAll(MWorldColl.java:72)
[11:55:51 WARN]:        at com.massivecraft.massivesharding.MassiveSharding.onEnable(MassiveSharding.java:147)
[11:55:51 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[11:55:51 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[11:55:51 WARN]:        at com.massivecraft.massivelag.inject.event.MassiveLagPluginLoader.enablePlugin(MassiveLagPluginLoader.java:220)
[11:55:51 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[11:55:51 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356)
[11:55:51 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316)
[11:55:51 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402)
[11:55:51 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370)
[11:55:51 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325)
[11:55:51 WARN]:        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211)
[11:55:51 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505)
[11:55:51 WARN]:        at java.lang.Thread.run(Unknown Source)
[11:55:51 WARN]: Caused by: java.lang.NullPointerException
[11:55:51 WARN]:        at com.worldcretornica.plotme.defaultgenerator.DefaultChunkGenerator.generateExtBlockSections(DefaultChunkGenerator.java:44)
[11:55:51 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:53)
[11:55:51 WARN]:        at net.minecraft.server.v1_8_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:140)
[11:55:51 WARN]:        ... 25 more
[11:55:51 INFO]: [MassiveSharding 1.0.0] ... enabling the world PlotMe1 failed.
```

```
[11:55:59 INFO]: [PlotMe] Starting to load plots for world plotme1
[11:55:59 WARN]: Exception in thread "Craft Scheduler Thread - 1"
[11:55:59 WARN]: org.apache.commons.lang.UnhandledException: Plugin PlotMe v0.17-SNAPSHOT generated an exception while executing task 22
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.worldcretornica.plotme_core.storage.Database$2.run(Database.java:332)
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

[11:55:59 INFO]: [PlotMe] Starting to load plots for world plotworld
[11:55:59 WARN]: Exception in thread "Craft Scheduler Thread - 2"
[11:55:59 WARN]: org.apache.commons.lang.UnhandledException: Plugin PlotMe v0.17-SNAPSHOT generated an exception while executing task 23
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.worldcretornica.plotme_core.storage.Database$2.run(Database.java:332)
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

**Comment by oloflarsson** [comment]
Also
```
[12:10:22 INFO]: [PlotMe] Enabling PlotMe v0.17-SNAPSHOT
[12:10:22 WARN]: java.sql.SQLException: Can not issue data manipulation statements with executeQuery().
[12:10:22 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
[12:10:22 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
[12:10:22 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
[12:10:22 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
[12:10:22 WARN]:        at com.mysql.jdbc.StatementImpl.checkForDml(StatementImpl.java:434)
[12:10:22 WARN]:        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1388)
[12:10:22 WARN]:        at com.worldcretornica.plotme_core.storage.MySQLConnector.createTables(MySQLConnector.java:47)
[12:10:22 WARN]:        at com.worldcretornica.plotme_core.PlotMe_Core.enable(PlotMe_Core.java:75)
[12:10:22 WARN]:        at com.worldcretornica.plotme_core.bukkit.PlotMe_CorePlugin.onEnable(PlotMe_CorePlugin.java:70)
[12:10:22 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[12:10:22 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[12:10:22 WARN]:        at com.massivecraft.massivelag.inject.event.MassiveLagPluginLoader.enablePlugin(MassiveLagPluginLoader.java:220)
[12:10:22 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[12:10:22 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356)
[12:10:22 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316)
[12:10:22 WARN]:        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:153)
[12:10:22 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505)
[12:10:22 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by oloflarsson** [comment]
Also
```
[12:45:39 INFO]: Cayorion issued server command: /plot claim
[12:45:39 ERROR]: [PlotMe] Insert Exception :
[12:45:39 ERROR]: [PlotMe] [SQLITE_CONSTRAINT]  Abort due to constraint violation (plotmecore_plots.homeX may not be NULL)
```

**Comment by oloflarsson** [comment]
Out of curiosity, do you even bug test your plugins? :cry:

**Comment by MattBDev** [comment]
I do but I have stated MANY MANY MANY *MANY* times that 0.17 doesn't work yet. I haven't finished the SQL Rewrite and if you look at the code, many functions return null without doing any work.

**Comment by geekphazm** [comment]
And still the same error after 5 months...

**Comment by MattBDev** [comment]
@geekphazm if you are getting this error on a non-dev release of 0.17 then please post the logs here because I have fixed this
