### ISSUE TITLE
plotme causing 429

### ISSUE THREAD

**Issue by Lineah** [WorldCretornica/PlotMe-Core#229]
Ok about a week ago i started getting this error msg:

[00:16:39] [Craft Scheduler Thread - 26/INFO]: [PlotMe] Checking if conversion to UUID needed...
[00:16:39] [Craft Scheduler Thread - 26/INFO]: [PlotMe] Fetching 1 UUIDs from Mojang servers...
[00:16:40] [Craft Scheduler Thread - 26/WARN]: java.io.IOException: Server returned HTTP response code: 429 for URL: https://api.mojang.com/profiles/minecraft
[00:16:40] [Craft Scheduler Thread - 26/WARN]:  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[00:16:40] [Craft Scheduler Thread - 26/WARN]:  at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[00:16:40] [Craft Scheduler Thread - 26/WARN]:  at org.spigotmc.CachedMojangAPIConnection.getInputStream(CachedMojangAPIConnection.java:108)
[00:16:40] [Craft Scheduler Thread - 26/WARN]:  at com.worldcretornica.plotme_core.utils.UUIDFetcher.call(UUIDFetcher.java:112)
[00:16:40] [Craft Scheduler Thread - 26/WARN]:  at com.worldcretornica.plotme_core.SqlManager$2.run(SqlManager.java:1884)
[00:16:40] [Craft Scheduler Thread - 26/WARN]:  at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(Craf

Since this error has occured no plots are protected, I have removed the plotme jar etc and re installed the plugins but nothing is stopping it. It spams about every 30 seconds or so.

Any assistance would be greatly appreciated.

**Comment by Lineah** [comment]
http://pastebin.com/mADmg7Qw

**Comment by MattBDev** [comment]
Duplicate and this is nothing we can fix as it is a mojang issue

**Comment by MattBDev** [comment]
@Lineah I also want to let you know I am making modifications to the UUID Fetcher and the error message will not spit out a bunch of ugly stuff like it did for you. It will be a one line message explaining what happened.
