### ISSUE TITLE
MV CREATE <WORLD> NORMAL -G PLOTME-DEFAULTGENERATOR [ERROR]

### ISSUE THREAD

**Issue by bosslorenz** [WorldCretornica/PlotMe-Core#249]
[15:23:55] [Server thread/ERROR]: Could not pass event WorldLoadEvent to Multiverse-Core v2.5-b691
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.createWorld(CraftServer.java:924) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:463) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:421) [Multiverse-Core-2.5.jar:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:229) [Multiverse-Core-2.5.jar:?]
	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114) [Multiverse-Core-2.5.jar:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) [Multiverse-Core-2.5.jar:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) [Multiverse-Core-2.5.jar:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) [Multiverse-Core-2.5.jar:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:897) [Multiverse-Core-2.5.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:632) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_67]
Caused by: net.minecraft.server.v1_8_R1.ReportedException: Exception generating new chunk
	at net.minecraft.server.v1_8_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:148) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:95) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getChunkAt(CraftWorld.java:124) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getBlockAt(CraftWorld.java:88) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getBlockAt(CraftWorld.java:558) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at com.onarandombox.MultiverseCore.utils.SimpleBlockSafety.playerCanSpawnHereSafely(SimpleBlockSafety.java:83) ~[?:?]
	at com.onarandombox.MultiverseCore.MVWorld.readSpawnFromWorld(MVWorld.java:410) ~[?:?]
	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:79) ~[?:?]
	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:56) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:427) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:402) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:377) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorld(WorldManager.java:364) ~[?:?]
	at com.onarandombox.MultiverseCore.listeners.MVWorldListener.loadWorld(MVWorldListener.java:57) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_67]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_67]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_67]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_67]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	... 22 more
Caused by: java.lang.NullPointerException
	at com.worldcretornica.plotme.defaultgenerator.DefaultChunkGenerator.generateExtBlockSections(DefaultChunkGenerator.java:47) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:53) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:140) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:95) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getChunkAt(CraftWorld.java:124) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getBlockAt(CraftWorld.java:88) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getBlockAt(CraftWorld.java:558) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at com.onarandombox.MultiverseCore.utils.SimpleBlockSafety.playerCanSpawnHereSafely(SimpleBlockSafety.java:83) ~[?:?]
	at com.onarandombox.MultiverseCore.MVWorld.readSpawnFromWorld(MVWorld.java:410) ~[?:?]
	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:79) ~[?:?]
	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:56) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:427) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:402) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:377) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorld(WorldManager.java:364) ~[?:?]
	at com.onarandombox.MultiverseCore.listeners.MVWorldListener.loadWorld(MVWorldListener.java:57) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_67]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_67]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_67]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_67]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	... 22 more
[15:23:55] [Server thread/WARN]: net.minecraft.server.v1_8_R1.ReportedException: Exception generating new chunk
[15:23:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:148)
[15:23:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116)
[15:23:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:95)
[15:23:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getChunkAt(CraftWorld.java:124)
[15:23:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getBlockAt(CraftWorld.java:88)
[15:23:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.getBlockAt(CraftWorld.java:558)
[15:23:55] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.SimpleBlockSafety.playerCanSpawnHereSafely(SimpleBlockSafety.java:83)
[15:23:55] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MVWorld.readSpawnFromWorld(MVWorld.java:410)
[15:23:55] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:79)
[15:23:55] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:56)
[15:23:55] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:427)
[15:23:55] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:229)
[15:23:55] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114)
[15:23:55] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[15:23:55] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[15:23:55] [Server thread/WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[15:23:55] [Server thread/WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:897)
[15:23:55] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[15:23:55] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[15:23:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[15:23:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:632)
[15:23:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353)
[15:23:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317)
[15:23:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[15:23:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[15:23:55] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[15:23:55] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[15:23:55] [Server thread/WARN]: 	at com.worldcretornica.plotme.defaultgenerator.DefaultChunkGenerator.generateExtBlockSections(DefaultChunkGenerator.java:47)
[15:23:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:53)
[15:23:55] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:140)
[15:23:55] [Server thread/WARN]: 	... 25 more
[15:23:55] [Server thread/INFO]: [0;31;1mAn internal error occurred when attempting to perform this command.[m
[15:23:55] [Server thread/INFO]: [0;31;1mDetails were printed to the server console and logs, please add that to your bug report.[m

**Comment by MattBDev** [comment]
BAD! Don't post an error like this ever again. this is not a bug, this is an error on your part.

**Comment by bosslorenz** [comment]
Sorry for posting here, my problem solved. When I tried to create it with another world name like *plotworld* it says Complete. But when trying to use name *Creative* it gives me failed . BTW thanks for 
the appreciation.

**Comment by EvilOlaf** [comment]
Do not use uppercase letters in world names. There is no standard between different plugins for case sensitivity so this can cause problems. So you always want to use lowercase world names.
