### ISSUE TITLE
Creating World failed

### ISSUE THREAD

**Issue by DutchUser** [WorldCretornica/PlotMe-Core#279]
If i try to create an plotworld with
 /mv create PlotWorldx32 normal -g PlotMe-DefaultGenerator
this error came on the console
(ingame 'FAILED'

19.05 00:13:39 [Server] WARN at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
19.05 00:13:39 [Server] WARN at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
19.05 00:13:39 [Server] WARN at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
19.05 00:13:39 [Server] WARN at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
19.05 00:13:39 [Server] WARN at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
19.05 00:13:39 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
19.05 00:13:39 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
19.05 00:13:39 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
19.05 00:13:39 [Server] WARN at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:897)
19.05 00:13:39 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
19.05 00:13:39 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
19.05 00:13:39 [Server] WARN at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
19.05 00:13:39 [Server] WARN at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114)
19.05 00:13:39 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:229)
19.05 00:13:39 [Server] WARN at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:421)
19.05 00:13:39 [Server] WARN at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
19.05 00:13:39 [Server] WARN at org.bukkit.Bukkit.createWorld(Bukkit.java:463)
19.05 00:13:39 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.CraftServer.createWorld(CraftServer.java:920)
19.05 00:13:39 [Server] WARN at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:95)
19.05 00:13:39 [Server] WARN at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116)
19.05 00:13:39 [Server] WARN at net.minecraft.server.v1_8_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:148)
19.05 00:13:39 [Server] WARN net.minecraft.server.v1_8_R1.ReportedException: Exception generating new chunk

**Comment by DutchUser** [comment]
Sorry the issue was that i must edit the config xD
