### ISSUE TITLE
ClassCastException BukkitPlayer at PlotResetEvent.java:39 with getReseter

### ISSUE THREAD

**Issue by MakerTim** [WorldCretornica/PlotMe-Core#331]
Try to use the API to make a confirm step in the reset/dispose/clear command, because my admins are clearing without thinking...
getting a ClassCastException at PlotResetEvent.java:39   * decompield http://puu.sh/iTy5n.png *
at version 0.16.3 of PlotMe

My code:
http://puu.sh/iTycy.png

StackTrace:
Caused by: java.lang.ClassCastException: com.worldcretornica.plotme_core.bukkit.api.BukkitPlayer cannot be cast to com.worldcretornica.plotme_core.bukkit.api.BukkitCommandSender
	at com.worldcretornica.plotme_core.bukkit.event.PlotResetEvent.getReseter(PlotResetEvent.java:39) ~[?:?]
	at nl.makertim.plotmeconfirm.PlotMeConfirmHandler.onClear(PlotMeConfirmHandler.java:61) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-fcb68de-1e56438]

while searching for the code on the github, coudnt find the code to qoute...

**Comment by MattBDev** [comment]
You can't cast the bukkit api to plotme api. This is Java Casting 101.
