### ISSUE TITLE
Could not load DefaultGenerator.jar

### ISSUE THREAD

**Issue by APlant641** [WorldCretornica/PlotMe-Core#351]
When starting the server, i get the following error: 

```
[15:03:02] [Server thread/ERROR]: Could not load 'plugins\PlotMe-DefaultGenerator.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/worldcretornica/plotme_core/bukkit/api/IBukkitPlotMe_GeneratorManager
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[craftbukkit.jar:git-Spigot-f94fe8f-219686b]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[craftbukkit.jar:git-Spigot-f94fe8f-219686b]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:275) [craftbukkit.jar:git-Spigot-f94fe8f-219686b]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [craftbukkit.jar:git-Spigot-f94fe8f-219686b]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [craftbukkit.jar:git-Spigot-f94fe8f-219686b]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [craftbukkit.jar:git-Spigot-f94fe8f-219686b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.NoClassDefFoundError: com/worldcretornica/plotme_core/bukkit/api/IBukkitPlotMe_GeneratorManager
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_31]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[craftbukkit.jar:git-Spigot-f94fe8f-219686b]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit.jar:git-Spigot-f94fe8f-219686b]
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.worldcretornica.plotme_core.bukkit.api.IBukkitPlotMe_GeneratorManager
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_31]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_31]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_31]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[craftbukkit.jar:git-Spigot-f94fe8f-219686b]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[craftbukkit.jar:git-Spigot-f94fe8f-219686b]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_31]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[craftbukkit.jar:git-Spigot-f94fe8f-219686b]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit.jar:git-Spigot-f94fe8f-219686b]
	... 6 more
```

I'm using the PlotMe download from Spigot, marked as version 0.16.3, released on the 11th of July. 
Spigot versioin is git-Spigot-f94fe8f-219686b (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT)

Generator version according to the plugin.yml is 0.16.1.

Should also note that both jar's are in the plugins folder and that i only just updated from 0.13.

**Comment by APlant641** [comment]
I have fixed this by altering the plugin.yml of DefaultGenerator:
turned softdepend into depend, and now it loaded like a dream.
