### ISSUE TITLE
Converting Problem?

### ISSUE THREAD

**Issue by download042** [WorldCretornica/PlotMe-Core#361]
Dear developer,

I use version 0.13b of PlotMe, and i tried to update it to v0.16.3, but i could not. I tried the Legacy converter, and it said that the conversion was a success, but it still didn't work, players couldn't use /plotme home (plot not found error). I tried to convert it multiple times without any success, and i had to ask the hosting to restore to the previous backup of the plugin.

Could you help me with this issue?

Sincerely, Download042

**Comment by EvilOlaf** [comment]
Hard to tell without log output as well as running server version for example.

**Comment by Maescool** [comment]
Legacy converter if for converting from 0.16 to 0.17
plotme 0.15 does convert from i think from 0.13d to 0.16

**Comment by download042** [comment]
I installed v0.15 as you said..
And i got this error:

08.08 21:30:02 [Server] ERROR null
08.08 21:30:02 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'plotme' in plugin PlotMe v0.15.2
08.08 21:30:02 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot_1.8.jar:git-Spigot-dbe012b-61ef214]
08.08 21:30:02 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot_1.8.jar:git-Spigot-dbe012b-61ef214]
08.08 21:30:02 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot_1.8.jar:git-Spigot-dbe012b-61ef214]
08.08 21:30:02 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133) [spigot_1.8.jar:git-Spigot-dbe012b-61ef214]
08.08 21:30:02 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [spigot_1.8.jar:git-Spigot-dbe012b-61ef214]
08.08 21:30:02 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot_1.8.jar:git-Spigot-dbe012b-61ef214]
08.08 21:30:02 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot_1.8.jar:git-Spigot-dbe012b-61ef214]
08.08 21:30:02 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_1.8.jar:git-Spigot-dbe012b-61ef214]
08.08 21:30:02 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_40]
08.08 21:30:02 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_40]
08.08 21:30:02 [Server] INFO at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot_1.8.jar:git-Spigot-dbe012b-61ef214]
08.08 21:30:02 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot_1.8.jar:git-Spigot-dbe012b-61ef214]
08.08 21:30:02 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot_1.8.jar:git-Spigot-dbe012b-61ef214]
08.08 21:30:02 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot_1.8.jar:git-Spigot-dbe012b-61ef214]
08.08 21:30:02 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot_1.8.jar:git-Spigot-dbe012b-61ef214]
08.08 21:30:02 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
08.08 21:30:02 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
08.08 21:30:02 [Server] INFO at com.worldcretornica.plotme_core.PlotMeCoreManager.getFirstWorld(PlotMeCoreManager.java:318) ~[?:?]
08.08 21:30:02 [Server] INFO at com.worldcretornica.plotme_core.commands.CmdHome.exec(CmdHome.java:30) ~[?:?]
08.08 21:30:02 [Server] INFO at com.worldcretornica.plotme_core.bukkit.BukkitCommand.onCommand(BukkitCommand.java:212) ~[?:?]
08.08 21:30:02 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot_1.8.jar:git-Spigot-dbe012b-61ef214]
08.08 21:30:02 [Server] INFO ... 15 more

wtf?

**Comment by download042** [comment]
I use Spigot, 1.8

**Comment by Maescool** [comment]
Make sure you also have the propper default generator for that version, and also no other plotme versions are being loaded.
also make sure you have multiverse in there..
