### ISSUE TITLE
cant load DynmapPlotMe.jar

### ISSUE THREAD

**Issue by Burockk** [WorldCretornica/PlotMe-Core#66]
[14:31:51] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[14:31:51] [Server thread/ERROR]: Could not load 'plugins\DynmapPlotMe.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: dynmap
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:225) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:369) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:152) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]

**Comment by EvilOlaf** [comment]
```
[14:31:51] [Server thread/ERROR]: Could not load 'plugins\DynmapPlotMe.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: dynmap
```

DynmapPlotMe does not work without Dynmap. Get latest Dynmap from dev.bukkit.org


Invalid
