### ISSUE TITLE
Fire

### ISSUE THREAD

**Issue by mttprvst13** [WorldCretornica/PlotMe-Core#89]
I am trying to use MV and an MV sign portal to teleport between a plot world and a normal world. When ever I try to set a fire for a nether portal to teleport to the normal world from the plot world the fire goes out so fast that the portal can't light. PLZ HELP!
[Pastebin] (http://pastebin.com/vbzsriyW)

**Comment by EvilOlaf** [comment]
It is recommended to use Bukkit/Spigot 1.8 for PlotMe 0.15.x.
If you want to stay at 1.7 you should use 0.13f which can be downloaded here: http://dev.bukkit.org/bukkit-plugins/plotme/files/36-v0-13f/

**Comment by mttprvst13** [comment]
Alright ill try, will it still work with my current stuff?

**Comment by EvilOlaf** [comment]
In order to use dynmap with your plot world you need to get the older dynmap addon for plotme. The one shipped with 0.15 would not work.

Also you may need to downgrade WorldEdit to 5.x. You can try running WorldEdit6. If everything works fine just leave it that way. Otherwise get the latest WE5 version.
That should not affect your other plugins.

**Comment by mttprvst13** [comment]
Alright I'm getting PlotMe 0.13f after I backup my server.

**Comment by EvilOlaf** [comment]
> after I backup my server.

Very commendable.

**Comment by mttprvst13** [comment]
Ya I just started my server with the later version of Dynmap, getting the older one. And thank you SO incredibly much for all your help, it really means a lot to me.

**Comment by mttprvst13** [comment]
Which version of dynmap should I get exactly?

**Comment by EvilOlaf** [comment]
Misunderstanding. You dont need to downgrade dynmap itself, just the plotme addon for it ;)

@MattBDev I don't know if there is a problem with fire, hard to imaginate. For my part I could not reproduce.

**Comment by mttprvst13** [comment]
alright, which version, 0.2 or 0.1?

**Comment by EvilOlaf** [comment]
Here you go: http://dev.bukkit.org/bukkit-plugins/dynmapplotme/
Grab the latest version.

**Comment by mttprvst13** [comment]
alright, Thank you so much ;-)

**Comment by mttprvst13** [comment]
Yep, that fixed the dynmap problem, thank you for that.

**Comment by mttprvst13** [comment]
but the fire is still not working :'(

**Comment by EvilOlaf** [comment]
Then I have no idea. I am sure that this is not related to PlotMe because I know definitely that fire works with 0.13f.
Check EssentialsProtect and EssentialsAntiBuild for any settings that prevent fire. Maybe you can find the problem there. I can not help you with them because I never used them.
Also check if you have all needed build permissions for your plot world.
Are you op? Did you try to use the lighter close to the world spawn? Check spawn protection.

**Comment by mttprvst13** [comment]
I am now getting this error: 

```[15:37:58 ERROR]: Could not pass event PlayerJoinEvent to PlotMe v0.13f
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.PlayerList.c(PlayerList.java:251) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.PlayerList.a(PlayerList.java:138) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.LoginListener.c(LoginListener.java:76) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.LoginListener.a(LoginListener.java:42) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:160) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(SourceFile:134) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:667) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:258) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:558) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:469) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getMask()Lcom/sk89q/worldedit/masks/Mask;
	at com.worldcretornica.plotme.PlotWorldEdit.setMask(PlotWorldEdit.java:61) ~[?:?]
	at com.worldcretornica.plotme.PlotWorldEdit.setMask(PlotWorldEdit.java:18) ~[?:?]
	at com.worldcretornica.plotme.listener.PlotWorldEditListener.onPlayerJoin(PlotWorldEditListener.java:78) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_65]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	... 14 more```

**Comment by EvilOlaf** [comment]
Known exception. Is related to WorldEdit 6. Just try if it affects your gameplay. If not, ignore it.

**Comment by Bobcat00** [comment]
"a fire for a nether portal to teleport to the normal world from the plot world"

I think you'll find that if you get the portal lit, it won't work as you expect.  CraftBukkit sees the lit portal, gets confused and teleports the player to the Nether instead of your intended destination.  You can fill the portal with water if you want some sort of effect.  Multiverse-Portals will contain the water within the portal.

**Comment by MattBDev** [comment]
Portals won't lite if the plotworld is not your default world.
