### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by dannyiscool4** [WorldCretornica/PlotMe-Core#90]
i cant execute a command with /plotme auto or claim he says its not a plotworld en gives errors

[07-01 16:56:47 ] [Server] ERROR null
[07-01 16:56:47 ] [Server] [Informatie] org.bukkit.command.CommandException: Unhandled exception executing command 'p' in plugin PlotMe v0.15.2
[07-01 16:56:47 ] [Server] [Informatie] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot1.8.old.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
[07-01 16:56:47 ] [Server] [Informatie] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot1.8.old.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
[07-01 16:56:47 ] [Server] [Informatie] at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[spigot1.8.old.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
[07-01 16:56:47 ] [Server] [Informatie] at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043) [spigot1.8.old.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
[07-01 16:56:47 ] [Server] [Informatie] at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880) [spigot1.8.old.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
[07-01 16:56:47 ] [Server] [Informatie] at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot1.8.old.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
[07-01 16:56:47 ] [Server] [Informatie] at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot1.8.old.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
[07-01 16:56:47 ] [Server] [Informatie] at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot1.8.old.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
[07-01 16:56:47 ] [Server] [Informatie] at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot1.8.old.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
[07-01 16:56:47 ] [Server] [Informatie] at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot1.8.old.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
[07-01 16:56:47 ] [Server] [Informatie] at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot1.8.old.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
[07-01 16:56:47 ] [Server] [Informatie] at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot1.8.old.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
[07-01 16:56:47 ] [Server] [Informatie] at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot1.8.old.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
[07-01 16:56:47 ] [Server] [Informatie] at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot1.8.old.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
[07-01 16:56:47 ] [Server] [Informatie] Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
[07-01 16:56:47 ] [Server] [Informatie] at com.worldcretornica.plotme_core.PlotMeCoreManager.getFirstWorld(PlotMeCoreManager.java:318) ~[?:?]
[07-01 16:56:47 ] [Server] [Informatie] at com.worldcretornica.plotme_core.commands.CmdAuto.exec(CmdAuto.java:26) ~[?:?]
[07-01 16:56:47 ] [Server] [Informatie] at com.worldcretornica.plotme_core.bukkit.BukkitCommand.onCommand(BukkitCommand.java:136) ~[?:?]
[07-01 16:56:47 ] [Server] [Informatie] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot1.8.old.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
[07-01 16:56:47 ] [Server

**Comment by MattBDev** [comment]
Please refer to the guide on the resource page for fixing this.

**Comment by EvilOlaf** [comment]
Whenever you post logs or errors either use markdown or pastebin, please. Noone likes to look at this unformatted waste.
